# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/taimen/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    abl \
    aes \
    cmnlib \
    cmnlib64 \
    devcfg \
    hyp \
    keymaster \
    laf \
    modem \
    pmic \
    rpm \
    tz \
    xbl
